contact_links:
  - name: ğŸ™Œ Contribution guide
    url: https://github.com/nicksp/.github/blob/main/CONTRIBUTING.md
    about: Please read through before making contributions.
  - name: â‰ï¸ How to make a reproduction?
    url: https://stackoverflow.com/help/minimal-reproducible-example
    about: Reproduction is very important for maintainer to help on your issues!
